### ISSUE TITLE
Dealing with wrong filenames...

### ISSUE THREAD

**Issue by beer4duke** [beer4all/rclone#14]
I have opened an issue in the xrootd go client: https://github.com/go-hep/hep/issues/758

When we have crappy filenames, the transfer does not work and this triggers a SIGSEGV violation in the xrootd client.

We could avoid the problem by not considering for transfer the files with a wrong filename...

```
2020/06/17 11:26:34 ERROR : go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.2/go.mod: 
Failed to copy: xrootd: error 3022: Unable to accept path name - illegal characters - use only A-Z a-
z 0-9 / SPACE .-_~#:^ /eos/mytestinstance/tmp/testic4/go/pkg/mod/github.com/!azure/azure-
pipeline-go@v0.2.2/go.mod; Invalid or incomplete multibyte or wide character
```

Let see what the xrootd hep devs reply to this issue...

**Comment by beer4duke** [comment]
Wrong file names are OK in xrootd (by OK I mean properly managed).
it looks like there is a bad combination when there are bad file names and shitload of files... and then `SIGSEGV` occurs.

Another thing: the client keeps plenty of TIME_WAIT connections as we are using plenty of parallel sessions and closing these: there is one connection per file that stays in TIME_WAIT status.
Outch...

**Comment by kiderrien** [comment]
Is the problem still present with the corrections made [here](https://github.com/beer4all/rclone/issues/16)?
