### ISSUE TITLE
Parse hash type and value

### ISSUE THREAD

**Issue by beer4duke** [beer4all/rclone#15]
https://github.com/beer4all/rclone/blob/3e885fcc825b2a8ecc5bc8a1271e2af562ee69bb/backend/xrootd/xrootd.go#L710

Is not defensive enough you should make sure that the first string is adler32, if not -> this is an error (wrong checksum type), and then parse the 8 remaining bytes as the adler32 hash.

xrootd endpoints can be configured to use a different checksum algorithm than adler32: this means that the returned checksum can be something else! And here you would just take 8 bytes somewhere in the returned string...

You just need to get what is before the space (checksum type) and after it (checksum value) and then you have something much more solid that will work with other checksums.

**Comment by kiderrien** [comment]
Adding of the option "disable_hashcheck" when configuring the remote which removes hash control (commit: `27d1b94`)

**Comment by kiderrien** [comment]
more defensive code. (Commit `242a25b`)
line 684
```
//resp.Data = "adler32 95ec3712\x00"
	stringdata := (strings.Split(string(resp.Data), " "))
	if stringdata[0] == "adler32" {
		hash :=(strings.Split(stringdata[1], "\x00"))[0]
		if len(hash)==8 {
				o.hash = hash
		}
	}
``` 
It will be necessary to change the code for the implementation of other hashes.
