### ISSUE TITLE
Improve code error handling

### ISSUE THREAD

**Issue by beer4duke** [beer4all/rclone#16]
Some functions are doing something if xrootd return code is not nil, but the nil returning parameters are going further in the execution...

Please look at @sbinet proposals here: https://github.com/go-hep/hep/issues/758

And be more defensive: if something returns an unexpected value just clean up the state in the function and return immediately with a meaningful return code for the calling function.

This way only valid execution is ongoing: errors and corner cases as treated ASAP and do not pollute the rest of the execution...

**Comment by kiderrien** [comment]
adding missing returns in commit `2cfbc55`
(line 858 and line 880)

**Comment by kiderrien** [comment]
Modification of the code so that it is more defensive at the level of opening xrootd.client and open. (Commit `242a25b` )

**Comment by kiderrien** [comment]
It should be checked that there is no leak (client or file not closed) at the end. Unfortunately i don't know how checked that.

**Comment by sbinet** [comment]
that's usually done with a `defer` statement.
_e.g.:_
```go
func foo() {
    f, err := os.Open(...)
    if err != nil { panic(err) }
    defer f.Close() // method will be called as soon as code path exits the foo function.
    // ...
}
```

see: https://tour.golang.org/flowcontrol/12

**Comment by kiderrien** [comment]
Thank you @sbinet 
I use defer each time I make a xrootd.client or I open a file to be sure that it is closed (except one which is used in other function normally closed at the end with a function).
