### ISSUE TITLE
Add verbose log output

### ISSUE THREAD

**Issue by beer4duke** [beer4all/rclone#3]
Several logs are required so that it is easier for users to report issues to developers when a command fails.

rclone -v should display all the called functions of the xrootd backend

-vv should display all the remove xrootd calls including the various xrootd urls.

For example ls should display which xrootd API is called iwth which arguments, so that one could easily try the command separately.

It is OK if output is very verbose as debug output is often redirected into a trace file sent to developers.

**Comment by kiderrien** [comment]
No modification at -v level because this is reserved for "INFO"

At -vv debug adds names of functions when they are used, also displays the uses of mkdir, move and remove
