### ISSUE TITLE
immutable tranfer

### ISSUE THREAD

**Issue by beer4duke** [beer4all/rclone#8]
add the xrootd backend option `immutable` that prevents file modifications.

It looks like this is the case currently as the open only creates new files but fails if the file already exists on the xrootd endpoint.

It can be a simple flag for the option -> if the immutable flag is set creates only new files no override, otherwise we should allow file modification.

@kiderrien please comment with the name of the `rclone` flag you chose: `--xrootd-immutable` ?
There may be some constraint on the name so that rclone pass it to the correct backend.

**Comment by beer4duke** [comment]
When looking in [rclone flags](https://rclone.org/flags/) the immutable flag can already be used as a global option:
```
      --immutable                            Do not modify files. Fail if existing files have been modified.
```

Can flags like this be added to the endpoint configuration `rclone config` ?

How ?

Can we add global flags if we set a flag specifically to a endpoint?

This flag may allow us to avoid implementing this in the backend.

**Comment by kiderrien** [comment]
Currently when opening a new file in the update function we use the option " OpenOptionsNew" hence the current problems when the file exists.
It may be possible to change this option, to modify when the file exists if it exists (in a classic way) and used - immutable if you don't want to modify them.

[List of options](https://godoc.org/go-hep.org/x/hep/xrootd/xrdfs#OpenOptions)
